"""add users table

Revision ID: 226ea56fbec1
Revises: 50f3c8bf7065
Create Date: 2026-04-27 19:50:50.530993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '226ea56fbec1'
down_revision: Union[str, Sequence[str], None] = '50f3c8bf7065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint(None, 'authors', ['name'])
    op.create_unique_constraint(None, 'libraries', ['address'])
    op.add_column('visitors', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'visitors', ['user_id'])
    op.create_foreign_key(None, 'visitors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.drop_constraint(None, 'visitors', type_='unique')
    op.drop_column('visitors', 'user_id')
    op.drop_constraint(None, 'libraries', type_='unique')
    op.drop_constraint(None, 'authors', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
