"""empty message

Revision ID: 50f3c8bf7065
Revises: d89e240bb7ad
Create Date: 2026-03-16 22:37:58.685703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50f3c8bf7065'
down_revision: Union[str, Sequence[str], None] = 'd89e240bb7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrears', sa.Column('library_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'arrears', 'libraries', ['library_id'], ['id'], ondelete='CASCADE')
    op.alter_column('visitors', 'birthday',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitors', 'birthday',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'arrears', type_='foreignkey')
    op.drop_column('arrears', 'library_id')
    # ### end Alembic commands ###
