"""delete user_id on visitors table

Revision ID: 849325036ff5
Revises: 226ea56fbec1
Create Date: 2026-04-29 18:38:38.342453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '849325036ff5'
down_revision: Union[str, Sequence[str], None] = '226ea56fbec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('visitors_user_id_key'), 'visitors', type_='unique')
    op.drop_constraint(op.f('visitors_user_id_fkey'), 'visitors', type_='foreignkey')
    op.drop_column('visitors', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('visitors_user_id_fkey'), 'visitors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('visitors_user_id_key'), 'visitors', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
